version: '3.7'
services:
    webscoket_frontend:
        build: conf/webscoket_frontend
        working_dir:  /usr/src/app
        container_name: webscoket_frontend
        volumes:
            - './src/frontend:/usr/src/app'
        ports:
        - '42179:42179'
        command: sh -c "npm install --force && ng serve --host 0.0.0.0 --port 42179 --disable-host-check"
        networks:
            - webserver
    websocket_server:
        build: conf/websocket/php-fpm
        working_dir: /src
        container_name: websocket_server
        volumes:
            - './src/websocket:/src'
            - './conf/websocket/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
        ports:
        - '9501:9501'
        command: sh -c "php server.php"
        networks:
            - webserver
networks:
    webserver:
        driver: bridge